### ISSUE TITLE
I have a problem to run the file.

### ISSUE THREAD

**Issue by PolloxxoCapo** [sc-workshop/better-sc-downloader#2]
I have python 7.0, I installed the requirements, but when I start the file main.py he report this error:
 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from lib.client import Client, HelloServerResponse
  File "C:\Users\pollo\Desktop\better-sc-downloader-main\lib\client.py", line 17, in <module>
    class Client:
  File "C:\Users\pollo\Desktop\better-sc-downloader-main\lib\client.py", line 40, in Client
    def content_version(self) -> list[int, int, int]:
TypeError: 'type' object is not subscriptable

**Comment by Daniil-SV** [comment]
The readme says:
``You need to have at least Python 3.9 for this to work.``
so yeah, just update python
